DROP DATABASE IF EXISTS `rest_db`;
CREATE DATABASE `rest_db`;
use `rest_db`;
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE
);
CREATE TABLE auth(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255) NOT NULL UNIQUE,
auth_key VARCHAR(255)
);